apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    servicebroker: sb-instanceid-rabbitmq
  name: sb-instanceid-rabbitmq
spec:
  replicas: 1
  selector:
    servicebroker: sb-instanceid-rabbitmq
  template:
    metadata:
      labels:
        servicebroker: sb-instanceid-rabbitmq
    spec:
      containers:
      - image: rabbitmq:3-management
        name: sb-instanceid-rabbitmq
        resources:
          limits:
            cpu: 0.1
        env:
          - name: RABBITMQ_ERLANG_COOKIE
            value: 3B694385-9169-42FF-8667-21E4F808F3AD
          - name: RABBITMQ_DEFAULT_USER
            value: admin
          - name: RABBITMQ_DEFAULT_PASS
            value: test1234
        ports:
        - containerPort: 5672
        - containerPort: 15672
